// <auto-generated />
using BLVP.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLVP.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BLVP.Entities.Counter", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("KEY");

                    b.Property<decimal>("Count")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COUNT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FORMAT");

                    b.Property<string>("NumberFormat")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NUMBERFORMAT");

                    b.HasKey("Key");

                    b.ToTable("IDCOUNTER", "TEST_SCHEMA");
                });
#pragma warning restore 612, 618
        }
    }
}
